EYE_CAPTURE_ID = 0
EYE_SIGHT_WIDTH = 640
EYE_SIGHT_HEIGHT = 480

WHEELS_PINS_LF = (5, 13)
WHEELS_PINS_LB = (19, 26)
WHEELS_PINS_RF = (12, 16)
WHEELS_PINS_RB = (20, 21)

EYE_SIMULATOR_ACTIVE = False

# EYE_SIMULATOR_ACTIVE = True
# EYE_SIMULATOR_DATASET = iter()


TORTOISE_WALK_PERIOD = 0.1

# fix it: it seems that only relative directory can by accessed by open
RECORDER_PATH = '.'

CONTROLLER_BAUDRATE = 9600
CONTROLLER_PORT_REGEX = 'usbmodem'
