EYE_CAPTURE_ID = 0
EYE_SIGHT_HEIGHT = 640
EYE_SIGHT_WIDTH = 320

WHEELS_PINS_LF = ()
WHEELS_PINS_LB = ()
WHEELS_PINS_RF = ()
WHEELS_PINS_RB = ()

TORTOISE_WALK_PERIOD = 0.1

RECORDER_PATH = '~/tortoise/'
